aws_dbt_snowflake_project:
  outputs:
    dev:
      account: ZQWFTEB-BS46531
      database: AIRBNB
      password: 4E2aeff157.6821
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: kazhar
      warehouse: COMPUTE_WH
  target: dev
spotify_dbt:
  outputs:
    dev:
      account: ew23855.eu-north-1.aws
      database: SPOTIFY_DB
      password: 4E2aeff157.6821
      role: ACCOUNTADMIN
      schema: transform
      threads: 3
      type: snowflake
      user: kazhar
      warehouse: COMPUTE_WH
  target: dev
